# TF-Luna LiDAR Configuration for Jetson Orin Nano

tfluna_publisher:
  ros__parameters:
    # Serial connection settings
    serial_port: "/dev/ttyTHS2"  # Jetson Orin Nano UART2 (pins 32/33) - separate from LD19
    baud_rate: 115200
    
    # ROS2 settings
    frame_id: "tfluna_link"
    publish_rate: 50.0  # Hz
    
    # Sensor specifications (from TF-Luna datasheet)
    field_of_view: 0.0349  # 2 degrees in radians
    min_range: 0.2  # meters
    max_range: 8.0  # meters (at 90% reflectivity)
    
    # Alternative I2C settings (if using I2C instead of UART)
    # Uncomment and modify the publisher node to use I2C
    # i2c_bus: 1  # I2C bus number
    # i2c_address: 0x10  # Default TF-Luna I2C address
